### ISSUE TITLE
Generate Random Slug on Server Side

### ISSUE THREAD

**Issue by SatvikG7** [NayamAmarshe/MagLit#10]
Users can run the following script in browser console to create short links with custom slugs

``` javascript

fetch("https://maglit.ml/api/create", {
    "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-language": "en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,af;q=0.6,mr;q=0.5",
        "content-type": "application/json",
        "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin"
    },
    "referrer": "https://maglit.ml/",
    "referrerPolicy": "strict-origin-when-cross-origin",
    "body": "{\"slug\":\"customslug\",\"password\":\"\",\"link\":\"https://eample.com\"}",
    "method": "POST",
    "mode": "cors",
    "credentials": "omit"
});

```

Generate Random Slug on Server Side to prevent users from generating custom slug

**Comment by SatvikG7** [comment]
@NayamAmarshe

**Comment by NayamAmarshe** [comment]
@SatvikG7 Thanks for reporting this and very sorry for the late reply, actually I was going to add the custom slug functionality too but the issue is with having a single page application with no scrollbars.

So for the time being, until I find a fix for the responsive issue when adding another input box, I'm allowing people to create custom slugs through the API endpoint.

**Comment by NayamAmarshe** [comment]
https://github.com/NayamAmarshe/MagLit/pull/15
